#!/bin/bash

# get package name from changelog - or set otherwise
CHNGLOG=$(find {,../,../../}debian/changelog  -type f -name changelog -print -quit 2>/dev/null)
PKGNAME=$(dpkg-parsechangelog -l "$CHNGLOG" -SSource)
PKGDATE=$(dpkg-parsechangelog -l "$CHNGLOG" -SDATE)
PKGVERS=$(dpkg-parsechangelog -l "$CHNGLOG" -SVersion)
PKGHELP="${PKGNAME}-help"

#HELPMD=$(find {,../,../../}data/${PKGHELP}.md  -type f -name ${PKGHELP}.md -print -quit 2>/dev/null)
HELPMD=$(find {,../,../../}data/help.md  -type f -name help.md -print -quit 2>/dev/null)
BASEDIR=$(realpath $(dirname $HELPMD))
SENDBUGS="https://forum.mxlinux.org/viewforum.php?f=96"

PODIR=help-po
TEMPMO=tmp-mo
[ -d $TEMPMO ] && rm -r $TEMPMO
[ -d $TEMPMO ] || mkdir $TEMPMO

export TEXTDOMAIN="${PKGHELP}"
export TEXTDOMAINDIR=$(realpath $TEMPMO)

METATITLE=$(sed -nr '/^#+/{s:::; s:\s+$::; p;q}' "$HELPMD") 

GETTEXT="cat<<EOF"
GETTEXT+=$'\n'
GETTEXT+=$( { 
    cat "$HELPMD";
    } |
    sed -r '
        s/^[[:space:]]+//;
        s/[[:space:]]+$//;
        /^[[:alpha:]]/,/^$/{/^$/!{H;d}; /^$/{x; s:\n: :g; s/^[[:space:]]+//; s/[[:space:]]+$//; s/$/\n/;}};
        /^(Version:?|Last updated:?)/!{
           s/^((#+)|([*]|[0-9]+[.]) |)(([*]+)?([[:alnum:]][^\n*]*)([*]+)?([\n]*$))/\1\5$(gettext "\6")\7\8/;
           /^(Version:?|Last updated:?)/s//$(gettext "\1")/;
           /^((<sub>)*)(Version:?|Last updated:?)/s//\1$(gettext "\3")/;
           s/^(#+)/$(printf "\1")/;
           }; 
        '
    )

GETTEXT+=$'\n'"EOF"

