#!/bin/bash

#set -x

unset TEMPMO PODIR HELPMD

source ./make-help-help
[ -n "$TEMPMO" ] && [ -d "$TEMPMO" ] || exit
[ -n "$PODIR"  ] && [ -d "$PODIR"  ] || exit
[ -n "$HELPMD" ] && [ -f "$HELPMD"  ] || exit

HELPHTML=help.html

POLANG=($( ls "$PODIR"/*.po 2>/dev/null))
POLANG=(${POLANG[@]##*/})
POLANG=(${POLANG[@]%.po})

export lang=
for lang in "en" "${POLANG[@]}"; do
    if [ "$lang" = "en" ]; then
        HREF=""
        HTML="$BASEDIR/${HELPHTML}"
        HTML_LANG="en-US"
        HTML_DIR="ltr"

    else
        HREF="../"
        HTML="$BASEDIR/$lang/${HELPHTML}"
        HTML_LANG="${lang//_/-}"
        # FIXME
        HTML_DIR="ltr"   
        PO=$PODIR/$lang.po
        [ -e $PO ] || continue
        [ -d $TEMPMO/$lang ]  || mkdir $TEMPMO/$lang
        [ -d $BASEDIR/$lang ] || mkdir $BASEDIR/$lang
        ln -s . $TEMPMO/$lang/LC_MESSAGES
        MO=$TEMPMO/$lang/$TEXTDOMAIN.mo
        msgfmt -o $MO $PO 
    fi

    TX_MARKDOWN=$(
    bash -c "unset LC_ALL
        export LANGUAGE=$lang
        export TEXTDOMAIN=${TEXTDOMAIN}
        export TEXTDOMAINDIR=${TEXTDOMAINDIR}
        ${GETTEXT}" | 
        sed -e "s/@VERSION@/${PKGVERS}/; 
        s/@DATE@/${PKGDATE}/;
        "
        )

    cat <<EOF | sed 's/^[[:space:]]*//' > "$HTML"
    <!doctype html>
    <html lang="${HTML_LANG}" dir="${HTML_DIR}">
    <head>
    <base href="${HREF}">
    <title>$(unset LC_ALL; export LANGUAGE=$lang; gettext "${METATITLE}")</title>
    </head>
    <body>
EOF

    python3 -m markdown <<<$TX_MARKDOWN >> "$HTML"

    cat <<EOF | sed 's/^[[:space:]]*//' >> "$HTML"
    
    </body>
    </html>
EOF

    # mx-viewer file://$(realpath "$HTML")

done

[ -n "$TEMPMO" ] && [ -d "$TEMPMO" ] && rm -r "$TEMPMO"
