#!/bin/bash

#  fehlix test project do not use
#: ${ORGANIZATION:=fehlix}
#: ${PROJECT:=testproject-do-not-use}

# set transifex organization and project name - if not set in environment alredy
: ${ORGANIZATION:=anticapitalista}
: ${PROJECT:=antix-development}

# set transifex resource name here  if it is not the package name
RESOURCE=user-installed-packages-mx


echodo() { echo "${@}";  ${@}; }

# need 'latest' transifex client
: ${TXBIN:=$(which tx)}
[ ! -x "$TXBIN" ] && echo "Error: transifex client not found!" && exit 1

# get package name from changelog
CHNGLOG=$(find {,../,../../}debian/changelog  -type f -name changelog -print -quit 2>/dev/null)
PKGNAME=$(dpkg-parsechangelog -l "$CHNGLOG" -SSource)
# set transifex resource to package name if not defined yet
: ${RESOURCE:=$PKGNAME}

# prepare transifex 
[ -d .tx         ] || mkdir -p .tx
[ -f .tx/config  ] && rm  .tx/config


cat <<EOF | tee .tx/config
[main]
host = https://www.transifex.com

[o:${ORGANIZATION}:p:${PROJECT}:r:${RESOURCE}]

file_filter = po/<lang>.po
minimum_perc = ${MINIMUM_PERC:=5}
resource_name = ${RESOURCE}
source_file = $PKGNAME.pot
source_lang = en
type = PO
EOF

# set transifex resource_id
RESOUCE_ID="${PROJECT}.${RESOURCE}"

echo "" 
echo "To push pot-file source to transifex run:" 
echo ${TXBIN} push --source  "$RESOUCE_ID"
